/*
Copyright 2014 Cloudbase Solutions Srl

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http ://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

#include "AttrToArgument.h"
#include "Message.h"
#include "Attribute.h"

static const int s_attrsToArgsDatapath[] =
{
    [OVS_USPACE_DP_ATTRIBUTE_NAME] = OVS_ARGTYPE_DATAPATH_NAME,
    [OVS_USPACE_DP_ATTRIBUTE_STATS] = OVS_ARGTYPE_DATAPATH_STATS,
    [OVS_USPACE_DP_ATTRIBUTE_UPCALL_PID] = OVS_ARGTYPE_DATAPATH_UPCALL_PORT_ID,
};

static const int s_attrsToArgsTunnel[] =
{
    [OVS_USPACE_TUNNEL_KEY_ATTRIBUTE_ID] = OVS_ARGTYPE_PI_TUNNEL_ID,
    [OVS_USPACE_TUNNEL_KEY_ATTRIBUTE_IPV4_SRC] = OVS_ARGTYPE_PI_TUNNEL_IPV4_SRC,
    [OVS_USPACE_TUNNEL_KEY_ATTRIBUTE_IPV4_DST] = OVS_ARGTYPE_PI_TUNNEL_IPV4_DST,
    [OVS_USPACE_TUNNEL_KEY_ATTRIBUTE_TOS] = OVS_ARGTYPE_PI_TUNNEL_TOS,
    [OVS_USPACE_TUNNEL_KEY_ATTRIBUTE_TTL] = OVS_ARGTYPE_PI_TUNNEL_TTL,
    [OVS_USPACE_TUNNEL_KEY_ATTRIBUTE_DONT_FRAGMENT] = OVS_ARGTYPE_PI_TUNNEL_DONT_FRAGMENT,
    [OVS_USPACE_TUNNEL_KEY_ATTRIBUTE_CSUM] = OVS_ARGTYPE_PI_TUNNEL_CHECKSUM,
};

static const int s_attrsToArgsPI[] =
{
    [OVS_USPACE_KEY_ATTRIBUTE_PRIORITY] = OVS_ARGTYPE_PI_PACKET_PRIORITY,
    [OVS_USPACE_KEY_ATTRIBUTE_IN_PORT] = OVS_ARGTYPE_PI_DP_INPUT_PORT,
    [OVS_USPACE_KEY_ATTRIBUTE_ETHERNET] = OVS_ARGTYPE_PI_ETH_ADDRESS,
    [OVS_USPACE_KEY_ATTRIBUTE_ETHERTYPE] = OVS_ARGTYPE_PI_ETH_TYPE,
    [OVS_USPACE_KEY_ATTRIBUTE_VLAN] = OVS_ARGTYPE_PI_VLAN_TCI,
    [OVS_USPACE_KEY_ATTRIBUTE_IPV4] = OVS_ARGTYPE_PI_IPV4,
    [OVS_USPACE_KEY_ATTRIBUTE_IPV6] = OVS_ARGTYPE_PI_IPV6,

    [OVS_USPACE_KEY_ATTRIBUTE_TCP] = OVS_ARGTYPE_PI_TCP,
    [OVS_USPACE_KEY_ATTRIBUTE_UDP] = OVS_ARGTYPE_PI_UDP,
    [OVS_USPACE_KEY_ATTRIBUTE_SCTP] = OVS_ARGTYPE_PI_SCTP,
    [OVS_USPACE_KEY_ATTRIBUTE_ICMP] = OVS_ARGTYPE_PI_ICMP,
    [OVS_USPACE_KEY_ATTRIBUTE_ICMPV6] = OVS_ARGTYPE_PI_ICMP6,
    [OVS_USPACE_KEY_ATTRIBUTE_ARP] = OVS_ARGTYPE_PI_ARP,
    [OVS_USPACE_KEY_ATTRIBUTE_ND] = OVS_ARGTYPE_PI_NEIGHBOR_DISCOVERY,
    [OVS_USPACE_KEY_ATTRIBUTE_MPLS] = OVS_ARGTYPE_PI_MPLS,
    [OVS_USPACE_KEY_ATTRIBUTE_DP_HASH] = OVS_ARGTYPE_PI_DATAPATH_HASH,
    [OVS_USPACE_KEY_ATTRIBUTE_RECIRC_ID] = OVS_ARGTYPE_PI_DATAPATH_RECIRCULATION_ID,

    [OVS_USPACE_KEY_ATTRIBUTE_SKB_MARK] = OVS_ARGTYPE_PI_PACKET_MARK,
    [OVS_USPACE_KEY_ATTRIBUTE_TUNNEL] = OVS_ARGTYPE_PI_TUNNEL_GROUP,
    [OVS_USPACE_KEY_ATTRIBUTE_MPLS] = OVS_ARGTYPE_PI_MPLS,
    [OVS_USPACE_KEY_ATTRIBUTE_ENCAP] = OVS_ARGTYPE_PI_ENCAP_GROUP,
};

static const int s_attrsToArgsFlow[] =
{
    [OVS_USPACE_FLOW_ATTRIBUTE_STATS] = OVS_ARGTYPE_FLOW_STATS,
    [OVS_USPACE_FLOW_ATTRIBUTE_TCP_FLAGS] = OVS_ARGTYPE_FLOW_TCP_FLAGS,
    [OVS_USPACE_FLOW_ATTRIBUTE_USED] = OVS_ARGTYPE_FLOW_TIME_USED,
    [OVS_USPACE_FLOW_ATTRIBUTE_CLEAR] = OVS_ARGTYPE_FLOW_CLEAR,
    [OVS_USPACE_FLOW_ATTRIBUTE_KEY] = OVS_ARGTYPE_FLOW_PI_GROUP,
    [OVS_USPACE_FLOW_ATTRIBUTE_ACTIONS] = OVS_ARGTYPE_FLOW_ACTIONS_GROUP,
    [OVS_USPACE_FLOW_ATTRIBUTE_MASK] = OVS_ARGTYPE_FLOW_MASK_GROUP
};

static const int s_attrsToArgsUpcall[] =
{
    [OVS_USPACE_UPCALL_ATTRIBUTE_PID] = OVS_ARGTYPE_ACTION_UPCALL_PORT_ID,
    [OVS_USPACE_UPCALL_ATTRIBUTE_USERDATA] = OVS_ARGTYPE_ACTION_UPCALL_DATA,
};

static const int s_attrsToArgsSample[] =
{
    [OVS_USPACE_SAMPLE_ATTRIBUTE_PROBABILITY] = OVS_ARGTYPE_ACTION_SAMPLE_PROBABILITY,
    [OVS_USPACE_SAMPLE_ATTRIBUTE_ACTIONS] = OVS_ARGTYPE_ACTION_SAMPLE_ACTIONS_GROUP,
};

static const int s_attrsToArgsActions[] =
{
    [OVS_USPACE_ACTION_ATTRIBUTE_OUTPUT] = OVS_ARGTYPE_ACTION_OUTPUT_TO_PORT,
    [OVS_USPACE_ACTION_ATTRIBUTE_USERSPACE] = OVS_ARGTYPE_ACTION_UPCALL_GROUP,
    [OVS_USPACE_ACTION_ATTRIBUTE_SET] = OVS_ARGTYPE_ACTION_SETINFO_GROUP,
    [OVS_USPACE_ACTION_ATTRIBUTE_PUSH_VLAN] = OVS_ARGTYPE_ACTION_PUSH_VLAN,
    [OVS_USPACE_ACTION_ATTRIBUTE_POP_VLAN] = OVS_ARGTYPE_ACTION_POP_VLAN,
    [OVS_USPACE_ACTION_ATTRIBUTE_SAMPLE] = OVS_ARGTYPE_ACTION_SAMPLE_GROUP,
    [OVS_USPACE_ACTION_ATTRIBUTE_PUSH_MPLS] = OVS_ARGTYPE_ACTION_PUSH_MPLS,
    [OVS_USPACE_ACTION_ATTRIBUTE_POP_MPLS] = OVS_ARGTYPE_ACTION_POP_MPLS,
    [OVS_USPACE_ACTION_ATTRIBUTE_RECIRC] = OVS_ARGTYPE_ACTION_RECIRCULATION,
    [OVS_USPACE_ACTION_ATTRIBUTE_HASH] = OVS_ARGTYPE_ACTION_HASH
};

static const int s_attrsToArgsPacket[] =
{
    [OVS_USPACE_PACKET_ATTRIBUTE_PACKET] = OVS_ARGTYPE_PACKET_BUFFER,
    [OVS_USPACE_PACKET_ATTRIBUTE_KEY] = OVS_ARGTYPE_PACKET_PI_GROUP,
    [OVS_USPACE_PACKET_ATTRIBUTE_ACTIONS] = OVS_ARGTYPE_PACKET_ACTIONS_GROUP,
    [OVS_USPACE_PACKET_ATTRIBUTE_USERDATA] = OVS_ARGTYPE_PACKET_USERDATA
};

static const int s_attrsToArgsPortOptions[] =
{
    [OVS_USPACE_TUNNEL_ATTRIBUTE_DST_PORT] = OVS_ARGTYPE_OFPORT_OPTION_DESTINATION_PORT,
};

static const int s_attrsToArgsPort[] =
{
    [OVS_USPACE_VPORT_ATTRIBUTE_PORT_NO] = OVS_ARGTYPE_OFPORT_NUMBER,
    [OVS_USPACE_VPORT_ATTRIBUTE_NAME] = OVS_ARGTYPE_OFPORT_NAME,
    [OVS_USPACE_VPORT_ATTRIBUTE_STATS] = OVS_ARGTYPE_OFPORT_STATS,
    [OVS_USPACE_VPORT_ATTRIBUTE_TYPE] = OVS_ARGTYPE_OFPORT_TYPE,
    [OVS_USPACE_VPORT_ATTRIBUTE_UPCALL_PID] = OVS_ARGTYPE_OFPORT_UPCALL_PORT_ID,
    [OVS_USPACE_VPORT_ATTRIBUTE_OPTIONS] = OVS_ARGTYPE_OFPORT_OPTIONS_GROUP,
};

typedef struct _OVS_ARG_GROUP_INFO
{
    OVS_ARGTYPE parent;
    const int* group;
    int max;
}OVS_ARG_GROUP_INFO, *POVS_ARG_GROUP_INFO;

static const OVS_ARG_GROUP_INFO s_argsToAttribs[OVS_ARG_GROUP_COUNT] =
{
    { OVS_ARGTYPE_PSEUDOGROUP_DATAPATH, s_attrsToArgsDatapath, OVS_USPACE_DP_ATTRIBUTE_MAX},
    { OVS_ARGTYPE_PSEUDOGROUP_FLOW, s_attrsToArgsFlow, OVS_USPACE_FLOW_ATTRIBUTE_MAX },
    { OVS_ARGTYPE_PSEUDOGROUP_OFPORT, s_attrsToArgsPort, OVS_USPACE_VPORT_ATTRIBUTE_MAX },
    { OVS_ARGTYPE_PSEUDOGROUP_PACKET, s_attrsToArgsPacket, OVS_USPACE_PACKET_ATTRIBUTE_MAX },

    { OVS_ARGTYPE_FLOW_PI_GROUP, s_attrsToArgsPI, OVS_USPACE_KEY_ATTRIBUTE_MAX },
    { OVS_ARGTYPE_FLOW_MASK_GROUP, s_attrsToArgsPI, OVS_USPACE_KEY_ATTRIBUTE_MAX },
    { OVS_ARGTYPE_FLOW_ACTIONS_GROUP, s_attrsToArgsActions, OVS_USPACE_ACTION_ATTRIBUTE_MAX },

    { OVS_ARGTYPE_PI_ENCAP_GROUP, s_attrsToArgsPI, OVS_USPACE_KEY_ATTRIBUTE_MAX },
    { OVS_ARGTYPE_PI_TUNNEL_GROUP, s_attrsToArgsTunnel, OVS_USPACE_TUNNEL_KEY_ATTRIBUTE_MAX },

    { OVS_ARGTYPE_PACKET_PI_GROUP, s_attrsToArgsPI, OVS_USPACE_KEY_ATTRIBUTE_MAX },
    { OVS_ARGTYPE_PACKET_ACTIONS_GROUP, s_attrsToArgsActions, OVS_USPACE_ACTION_ATTRIBUTE_MAX },

    { OVS_ARGTYPE_ACTION_UPCALL_GROUP, s_attrsToArgsUpcall, OVS_USPACE_UPCALL_ATTRIBUTE_MAX },
    { OVS_ARGTYPE_ACTION_SETINFO_GROUP, s_attrsToArgsPI, OVS_USPACE_KEY_ATTRIBUTE_MAX },
    { OVS_ARGTYPE_ACTION_SAMPLE_GROUP, s_attrsToArgsSample, OVS_USPACE_SAMPLE_ATTRIBUTE_MAX },

    { OVS_ARGTYPE_ACTION_SAMPLE_ACTIONS_GROUP, s_attrsToArgsActions, OVS_USPACE_ACTION_ATTRIBUTE_MAX },
    { OVS_ARGTYPE_OFPORT_OPTIONS_GROUP, s_attrsToArgsPortOptions, OVS_USPACE_TUNNEL_ATTRIBUTE_MAX },
};

static const OVS_ARG_GROUP_INFO* _FindGroup(OVS_ARGTYPE parentArgType, _Out_ int* pMax)
{
    for (int i = 0; i < OVS_ARG_GROUP_COUNT; ++i)
    {
        const OVS_ARG_GROUP_INFO* pGroup = s_argsToAttribs + i;

        if (parentArgType == pGroup->parent)
        {
            *pMax = pGroup->max;

            return pGroup;
        }
    }

    OVS_CHECK(__UNEXPECTED__);
    return NULL;
}

BOOLEAN AttrType_To_ArgType(UINT16 attrType, OVS_ARGTYPE parentArgType, OVS_ARGTYPE* pTypeAsArg)
{
    const OVS_ARG_GROUP_INFO* pGroup = NULL;
    int maxAttr = 0;
    ULONG argType = 0;

    pGroup = _FindGroup(parentArgType, &maxAttr);

    //TODO: the func should still return BOOLEAN
    OVS_CHECK_RET(pGroup, FALSE);
    OVS_CHECK_RET(attrType <= maxAttr, FALSE);

    argType = pGroup->group[attrType];
    OVS_CHECK_RET(argType != OVS_ARGTYPE_INVALID, FALSE);

    *pTypeAsArg = argType;

    return TRUE;
}